### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by walio** [walio/visualzoom#1]
- [ ] 使用异步方式调用？使用更“tornado”的方式？
- [x] 点击地图上的点展开详细信息
- [ ] 做好websocket的连接管理，断开重连等
- [ ] 检查内存时，迭代返回HTTP响应时，socket对象被占用，必须关闭后再发送请求看用户名密码是否正确，即是说只有一次机会。一般来说没问题，万一有特殊情况？
- [ ] 设置用户验证？
- [x] 做成插件形式，最大程度解耦
- [ ] 起个好名字!!!!!
- [ ] 参考rapid7的iotseeker，增加可以检测的类型
- [ ] 增加shodan的数据源
- [x] 命令行模式和服务器模式
- [ ] 当某个线程陷入阻塞时，整个服务器无法返回响应。是否能做成正常的服务器供多人访问？
